version: '3.8'

services:
  # Backend service (Node.js)
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app_backend
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app_backend/src
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - app_network
    command: ['npm', 'run', 'dev']

networks:
  app_network:
    driver: bridge
